@startuml
'https://plantuml.com/deployment-diagram

title Prompt Optimization Flow

node PromptOptimizer

actor LLM2
note bottom of LLM2
Test generator and
Prompt-Response Evaluator
model:
end note

storage persistent_storage
actor LLM
note bottom of LLM
Response to prompt
model:
end note

PromptOptimizer --> LLM2: (1) generate_test_tasks()

PromptOptimizer --> persistent_storage: (2) save test_suite

PromptOptimizer --> LLM: (3) chat(prompt)

PromptOptimizer --> LLM2: (4) evaluate_responses()

PromptOptimizer --> PromptOptimizer: (5) mutate(prompt) to new_prompt

@enduml